#!/bin/bash

echo "🔍 Checklist para testar o Codespace:"
echo ""
echo "1. ✅ Ambiente carrega em 2-3 minutos"
echo "2. ✅ Python 3.11 funciona"
echo "3. ✅ Qiskit instalado corretamente"
echo "4. ✅ Jupyter funciona"
echo "5. ✅ Notebook abre sem erro"
echo "6. ✅ Células executam normalmente"
echo ""
echo "🧪 Comandos para testar no terminal do Codespace:"
echo ""
echo "# Verificar Python"
echo "python --version"
echo ""
echo "# Verificar Qiskit"
echo "python -c 'import qiskit; print(f\"Qiskit: {qiskit.__version__}\")'"
echo ""
echo "# Verificar outras bibliotecas"
echo "python -c 'import numpy, matplotlib, jupyter; print(\"✅ Todas bibliotecas OK!\")'"
echo ""
echo "# Listar extensões do VS Code"
echo "code --list-extensions"
echo ""
echo "🚀 Se tudo funcionar, está pronto para o evento!"