#!/bin/bash

# Script de boas-vindas para Codespace
echo "🌟 ============================================= 🌟"
echo "    Bem-vindo ao Qiskit Workshop Codespace!"
echo "🌟 ============================================= 🌟"
echo ""
echo "🔬 Este ambiente já está configurado com:"
echo "   ✅ Python 3.11"
echo "   ✅ Qiskit e todas as dependências"
echo "   ✅ Jupyter Notebooks"
echo "   ✅ Extensões do VS Code"
echo ""
echo "📚 Para começar:"
echo "   1. Abra: notebooks/aula1_gerador_aleatorio.ipynb"
echo "   2. Execute as células sequencialmente"
echo "   3. Explore computação quântica!"
echo ""
echo "🚀 Comandos úteis:"
echo "   - jupyter lab: Iniciar Jupyter Lab"
echo "   - python -c 'import qiskit; print(qiskit.__version__)': Verificar Qiskit"
echo ""
echo "🌐 Este Codespace está pronto para uso!"
echo "🌟 ============================================= 🌟"